name: Update end date for bangumi

on:
  schedule:
    - cron: '0 4 1 * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Get current time
        id: current-time
        uses: srfrnk/current-time@master
        with:
          format: X

      - name: Set branch name
        id: branch-name
        run: echo "::set-output name=result::$BRANCH_NAME"
        env:
          BRANCH_NAME: "update-end-${{ steps.current-time.outputs.formattedTime }}"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Create a new branch
        run: git checkout -b ${{ steps.branch-name.outputs.result }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run bdh to update end date
        run: npx bangumi-data-helper end

      - name: Commit changes
        id: commit-changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update end date
          branch: ${{ steps.branch-name.outputs.result }}

      - name: Create pull request
        if: steps.commit-changes.outputs.changes_detected == 'true'
        run: |
          gh pr create -r $REVIEWER -a $REVIEWER -t "Auto end date update" -b "${{ steps.current-time.outputs.formattedTime }}"
        env:
          REVIEWER: wxt2005
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
